### ISSUE TITLE
cmdstan 2.18.1 installed, cannot run sample model on Windows 10

### ISSUE THREAD

**Issue by davidmanheim** [stan-dev/cmdstan#673]
#### Summary:
I have successfully installed cmdstan (I think) but I tried running the sample model, and get the below error

#### Description:
When running bernoulli I get about 10 pages of the warnings and errors of this output, followed by the failure at the end:

#### Reproducible Steps:
I installed on cmdstan 2.18.1 on Windows 10 on my machine, then run the model:
make bernoulli\bernoulli

#### Output
In file included from <command-line>:0:0:
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:87:5: error: stray '\2' in program
In file included from <command-line>:0:0:
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:87:984: warning: null character(s) ignored
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:87:986: warning: null character(s) ignored
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:87:999: warning: null character(s) ignored
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:87:1010: warning: null character(s) ignored
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:87:1021: warning: null character(s) ignored
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:87:1032: warning: null character(s) ignored
In file included from <command-line>:0:0:
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:1:1: error: expected unqualified-id before '!' token
 !<arch>
 ^
In file included from <command-line>:0:0:
./stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a:12:2: error: 'A' does not name a type
In file included from C:/RBuildTools/Rtools/mingw_64/x86_64-w64-mingw32/include/_mingw.h:282:0,
                 from C:/RBuildTools/Rtools/mingw_64/x86_64-w64-mingw32/include/crtdefs.h:10,
                 from C:/RBuildTools/Rtools/mingw_64/x86_64-w64-mingw32/include/stddef.h:7,
                 from C:/RBuildTools/Rtools/mingw_64/lib/gcc/x86_64-w64-mingw32/4.9.3/include/stddef.h:1,
                 from C:/RBuildTools/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/cstddef:45,
                 from stan/lib/stan_math/lib/boost_1.66.0/boost/config/compiler/gcc.hpp:165,
                 from stan/lib/stan_math/lib/boost_1.66.0/boost/config.hpp:39,
                 from stan/lib/stan_math/lib/boost_1.66.0/boost/lexical_cast.hpp:21,
                 from stan/src/stan/callbacks/writer.hpp:4,
                 from src/cmdstan/arguments/argument.hpp:4,
                 from src/cmdstan/arguments/argument_parser.hpp:4,
                 from src/cmdstan/command.hpp:4,
                 from src/cmdstan/main.cpp:1:
C:/RBuildTools/Rtools/mingw_64/x86_64-w64-mingw32/include/vadefs.h:12:32: error: expected declaration before end of line
 #pragma pack(push,_CRT_PACKING)
                                ^
make: *** [make/models:16: examples\bernoulli\bernoulli] Error 1

#### Current Version:
v2.18.1

**Comment by seantalts** [comment]
Do you know what version of RTools you have installed? Could you perhaps paste the full output after a `make clean-all` onto something like gist.github.com?

**Comment by wds15** [comment]
I think I had very similar error messages myself with the unit tests of stan-math under Windows... no idea what the problem was... since I can always move to a different platform I gave up. I wonder what the solution is.

**Comment by davidmanheim** [comment]
I'm running the most recent version of RTools, 3.5 IIRC.
(I'll try to rerun and put the full output online tomorrow.)

**Comment by davidmanheim** [comment]
Unfortunately, it has more output that windows allows me to keep in the cmd window.  The very first line is that examples\bernoulli\bernoulli "doesn't match the target pattern" (I scrolled up when it started so I could see the message. Windows is weird.) 
Here's the output I have: https://gist.github.com/davidmanheim/44b02610106b976b3097a4e1c69e3d37

If there is a way to suppress some output, I can do that and paste the results.  (I tried make -s and it changes nothing.)

**Comment by seantalts** [comment]
Those are all super weird... If you get a chance, could you try redirecting the output to a file? Basically something like
```
make clean-all
make examples/bernoulli/bernoulli >out.txt 2>&1 
```

**Comment by davidmanheim** [comment]
Right. Apologies for somehow forgetting how to do operating systems - 🤷‍♂️.

The gist linked above is now updated with the full output.

**Comment by slphyx** [comment]
I couldn't run the example too. (no error messages during the installation 2.18.1)
(Windows 10, RTools 3.5, cmdstan 2.18.1) 

I got exactly the same output as @davidmanheim but for the command (no exe)

make examples\\bernoulli\\bernoulli 


But when I added .exe (which we should do for Windows)
I got this instead


D:\Data-Work\Programs\cmdstan-2.18.1>make examples\\bernoulli\\bernoulli.exe

--- Translating Stan model to C++ code ---
bin'\'stanc.exe  examples\\bernoulli\\bernoulli.stan --o=examples\\bernoulli\\bernoulli.hpp
Model name=bernoulli_model
Input file=examples\bernoulli\bernoulli.stan
Output file=examples\bernoulli\bernoulli.hpp

--- Linking C++ model ---
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.66.0 -isystem stan/lib/stan_math/lib/sundials_3.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -I src -isystem stan/src -isystem stan/lib/stan_math/ -DFUSION_MAX_VECTOR_SIZE=12 -Wno-unused-local-typedefs -DEIGEN_NO_DEBUG -m64 -Wno-unused-but-set-variable -DNO_FPRINTF_OUTPUT -pipe   src/cmdstan/main.cpp -O3 -o examples\\bernoulli\\bernoulli.exe -include examples\\bernoulli\\bernoulli.hpp -include examples\\bernoulli\\USER_HEADER.hpp stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_3.1.0/lib/libsundials_idas.a
In file included from stan/src/stan/model/model_header.hpp:8:0,
                 from ./examples\bernoulli\bernoulli.hpp:3,
                 from <command-line>:0:
stan/src/stan/io/reader.hpp: In member function 'T stan::io::reader<T>::scalar_locscale_constrain(TL, TS)':
stan/src/stan/io/reader.hpp:709:16: error: 'locscale_constrain' is not a member of 'stan::math'
         return stan::math::locscale_constrain(scalar(), loc, scale);
                ^
stan/src/stan/io/reader.hpp: In member function 'T stan::io::reader<T>::scalar_locscale_constrain(TL, TS, T&)':
stan/src/stan/io/reader.hpp:727:16: error: 'locscale_constrain' is not a member of 'stan::math'
         return stan::math::locscale_constrain(scalar(), loc, scale, lp);
                ^
In file included from stan/src/stan/model/model_header.hpp:9:0,
                 from ./examples\bernoulli\bernoulli.hpp:3,
                 from <command-line>:0:
stan/src/stan/io/writer.hpp: In member function 'void stan::io::writer<T>::scalar_locscale_unconstrain(double, double, T&)':
stan/src/stan/io/writer.hpp:179:27: error: 'locscale_free' is not a member of 'stan::math'
         data_r_.push_back(stan::math::locscale_free(y, loc, scale));
                           ^
make: *** [makefile:108: examples\\bernoulli\\bernoulli.exe] Error 1

**Comment by davidmanheim** [comment]
Per other thread, this works in cmdstan 2.19.

Closing.
