### ISSUE TITLE
OpenCL problem in linux

### ISSUE THREAD

**Issue by joscani** [stan-dev/cmdstan#1140]
Hi. I'm using cmdstn 2-31 
My clinfo -l output is 
```
clinfo -l
Platform #0: NVIDIA CUDA
 `-- Device #0: NVIDIA GeForce GTX 1650
```
My make/local in cmdstan is 
```
# Enable the OpenCL backend
STAN_OPENCL=true
OPENCL_DEVICE_ID=0
OPENCL_PLATFORM_ID=0
```

I write this 
```
make clean-all
make examples/bernoulli/bernoulli
````
and  get
```
In file included from src/cmdstan/main.cpp:1:
src/cmdstan/command.hpp: In function ‘int cmdstan::command(int, const char**)’:
src/cmdstan/command.hpp:158:33: error: ‘open_platform_id’ was not declared in this scope; did you mean ‘opencl_platform_id’?
````
Any idea?

**Comment by WardBrian** [comment]
This looks like a typo introduced in https://github.com/stan-dev/cmdstan/pull/1134

I guess we aren’t testing opencl compilation at the cmdstan level? @rok-cesnovar @serban-nicusor-toptal 

This code hasn’t been released yet though, so if you’re using the release tarball of 2.31 I’m not sure how this would have happened.

**Comment by joscani** [comment]
Ok. In old cmdstan version. (2.26) opencl works for me. Thanks
